search_wp:
  ros__parameters:
    ciencia:
      x: 0.0
      y: 0.0
      w: 0.0
    literatura:
      x: 0.0
      y: 0.0
      w: 0.0
    historia:
      x: 0.0
      y: 0.0
      w: 0.0
    infantil:
      x: 0.0
      y: 0.0
      w: 0.0
    arr: ["ciencia", "literatura", "historia", "infantil"]
    size: 4
