search_wp:
  ros__parameters:
    waypoints:
      ciencia:
        position: {x: 1.0, y: 2.0, z: 0.0}
        orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
      literatura:
        position: {x: 3.0, y: 4.5, z: 0.0}
        orientation: {x: 0.0, y: 0.0, z: 0.707, w: 0.707}
      historia:
        position: {x: 5.2, y: 1.0, z: 0.0}
        orientation: {x: 0.0, y: 0.0, z: 1.0, w: 0.0}
      infantil:
        position: {x: 5.2, y: 1.0, z: 0.0}
        orientation: {x: 0.0, y: 0.0, z: 1.0, w: 0.0}
      arr: ["ciencia", "literatura", "historia", "infantil"]
